### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by kourner** [JunkyByte/deepcharuco#3]
"Thank you so much for your open-source contributions, this is great work! I am very interested in your code. Would it be possible for you to share the training data for the marker? I would greatly appreciate your help!"

**Comment by JunkyByte** [comment]
Hello, thank you! The data to train the networks is generated on the fly and not saved.
Check https://github.com/JunkyByte/deepcharuco#setup-for-training-and-inference-on-val-data

The only real data are the coco images which are used as backgrounds :)
